// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tcontext.Data;

#nullable disable

namespace KLKLKL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240621054739_table_Student")]
    partial class table_Student
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("KLKLKL.Models.cau1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Heigh")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("cau1");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("KLKLKL.Models.Student", b =>
                {
                    b.HasBaseType("KLKLKL.Models.cau1");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sonha")
                        .HasColumnType("INTEGER");

                    b.ToTable("cau2");
                });

            modelBuilder.Entity("KLKLKL.Models.Student", b =>
                {
                    b.HasOne("KLKLKL.Models.cau1", null)
                        .WithOne()
                        .HasForeignKey("KLKLKL.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
